services:
  wanda-python:
    image: wanda-python
    container_name: wanda-python
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn wanda_python.app:app --host 0.0.0.0 --port 8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVICE_NAME=${SERVICE_NAME}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - OTEL_ENDPOINT=${OTEL_ENDPOINT}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_tmp:/tmp/wanda_runner
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - wanda-network

volumes:
  runner_tmp:
    name: wanda_runner_tmp

networks:
  wanda-network:
    external: true